[tool.poetry]
name = "Poetry commit hooks"
version = "0.1.0"
description = ""
authors = ["null <null@null.local>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9.0"
pre-commit = "^3.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
